version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  chatbot:
    build: .
    container_name: ass1chatbot
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434
    tty: true
    stdin_open: true

volumes:
  ollama_data:
